### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by djerik** [ShiromMakkad/LedFx-balenaSound#2]
Building for Raspberry 3B+, I get the following build error in Balena:

Step 1/17 : FROM balenalib/raspberrypi3-alpine-node:latest as web-builder
 ---> 106df446d501
Step 2/17 : WORKDIR /usr/src
 ---> Running in 53c13da215c3
Removing intermediate container 53c13da215c3
 ---> 235ea5961c75
Step 3/17 : RUN install_packages git make npm
 ---> Running in a5875cce12ee
Here are a few details about this Docker image (For more information please visit https://www.balena.io/docs/reference/base-images/base-images/): 
Architecture: ARM v7 
OS: Alpine Linux 3.14 
Variant: run variant 
Default variable(s): UDEV=off 
The following software stack is preinstalled: 
Node.js v16.10.0, Yarn v1.22.4 
Extra features: 
- Easy way to install packages with `install_packages <package-name>` command 
- Run anywhere with cross-build feature  (for ARM only) 
- Keep the container idling with `balena-idle` command 
- Show base image details with `balena-info` command
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/armv7/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/armv7/APKINDEX.tar.gz
(1/6) Installing pcre2 (10.36-r0)
(2/6) Installing git (2.32.0-r0)
(3/6) Installing make (4.3-r0)
(4/6) Installing c-ares (1.17.2-r0)
(5/6) Installing nodejs (14.17.6-r0)
(6/6) Installing npm (7.17.0-r0)
Executing busybox-1.33.1-r3.trigger
OK: 109 MiB in 83 packages
Removing intermediate container a5875cce12ee
 ---> 996fc2c81935
Step 4/17 : RUN git clone https://github.com/badaix/snapweb.git snapweb
 ---> Running in 2ce34d8ef8da
Cloning into 'snapweb'...

Removing intermediate container 2ce34d8ef8da
 ---> 5f7dead64e80
Step 5/17 : RUN npm install --global --no-save typescript
 ---> Running in 9c2fee78a78d
added 1 package, and audited 2 packages in 2s
found 0 vulnerabilities
npm notice
 
npm
 notice New patch version of npm available! 7.24.0 -> 7.24.1
npm
 notice Changelog: <https://github.com/npm/cli/releases/tag/v7.24.1>
npm 
notice Run `npm install -g npm@7.24.1` to update!
npm notice 

Removing intermediate container 9c2fee78a78d
 ---> fca5b7984116
Step 6/17 : RUN cd snapweb && make
 ---> Running in df428723c4da
tsc --build page/tsconfig.json
page/snapstream.ts(912,112): error TS2339: Property 'outputLatency' does not exist on type 'AudioContext'.
page/snapstream.ts(912,151): error TS2339: Property 'outputLatency' does not exist on type 'AudioContext'.
page/snapstream.ts(913,107): error TS2339: Property 'outputLatency' does not exist on type 'AudioContext'.
make: *** [Makefile:6: tsc] Error 1

Removing intermediate container df428723c4da
The command '/bin/sh -c cd snapweb && make' returned a non-zero code: 2

**Comment by ShiromMakkad** [comment]
I just updated balena sound. See if it works

**Comment by djerik** [comment]
Thanks for looking into it.

multiroom-server builds ok now. But instead sound-supervisor fails - I am not sure if you prefer to have it as a new issue?

`Step 1/15 : FROM balenalib/raspberrypi3-node:12 as build
 ---> f74ba2e9692d
Step 2/15 : WORKDIR /usr/src
Using cache
 ---> 83309a707b86
Step 3/15 : COPY core/sound-supervisor/package*.json ./
 ---> 8a0aefabb56a
Step 4/15 : RUN npm install
 ---> Running in 365eb51946d2
Here are a few details about this Docker image (For more information please visit https://www.balena.io/docs/reference/base-images/base-images/): 
Architecture: ARM v7 
OS: Debian Buster 
Variant: run variant 
Default variable(s): UDEV=off 
The following software stack is preinstalled: 
Node.js v12.22.5, Yarn v1.22.4 
Extra features: 
- Easy way to install packages with `install_packages <package-name>` command 
- Run anywhere with cross-build feature  (for ARM only) 
- Keep the container idling with `balena-idle` command 
- Show base image details with `balena-info` command
npm WARN deprecated axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410

npm 
WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)

npm WARN deprecated @types/socket.io-parser@3.0.0: This is a stub types definition. socket.io-parser provides its own type definitions, so you do not need this installed.

> nodemon@2.0.13 postinstall /usr/src/node_modules/nodemon
> node bin/postinstall || exit 0
Love nodemon? You can now support the project via the open collective:
 > https://opencollective.com/nodemon/donate
npm notice created a lockfile as package-lock.json. You should commit this file.

npm WARN notsup Unsupported engine for @tmigone/pulseaudio@0.1.12: wanted: {"node":"12.4.x"} (current: {"node":"12.22.5","npm":"6.14.14"})
npm WARN notsup
 Not compatible with your version of node/npm: @tmigone/pulseaudio@0.1.12

npm WARN optional
 SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

npm WARN
 sound-supervisor@1.0.0 No repository field.



added 345 packages from 321 contributors and audited 347 packages in 14.774s
21 packages are looking for funding
  run `npm fund` for details
found 2 vulnerabilities (1 low, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
Removing intermediate container 365eb51946d2
 ---> 2baf16c4b559
Step 5/15 : COPY core/sound-supervisor/src ./src
 ---> 82ce34a89dd6
Step 6/15 : COPY core/sound-supervisor/tsconfig.json .
 ---> f688c917d65f
Step 7/15 : RUN npm run build
 ---> Running in 3209cccd56c0
> sound-supervisor@1.0.0 build /usr/src
> npm run clean && tsc --project tsconfig.json && cp -R src/ui build/ui && cp -R src/audio-block build/audio-block
> sound-supervisor@1.0.0 clean /usr/src
> rm -rf build
Removing intermediate container 3209cccd56c0
 ---> 74e481b08e40
Step 8/15 : COPY VERSION .
COPY failed: stat /var/lib/balena32/tmp/docker-builder635321944/VERSION: no such file or directory`

**Comment by djerik** [comment]
I tried to understand why it fails - but I could not find the reason. Let me know if I can be of any help?

**Comment by ShiromMakkad** [comment]
I noticed you forked this repo. Did you find the issue? I'm coming back to this repo after months and I'm having the same problem, and I don't really have any leads for fixing it.

**Comment by ShiromMakkad** [comment]
The issue was creating the VERSION file in the main folder
